export const MARKETDATA_USERCOINS_SUCCESS = 'MARKETDATA_USERCOINS_SUCCESS';
export const MARKETDATA_ALLCOINSLIST_SUCCESS = 'MARKETDATA_ALLCOINSLIST_SUCCESS';
export const MARKETDATA_ERROR = 'MARKETDATA_ERROR';