export const PORTFOLIO_SUCCESS = 'PORTFOLIO_SUCCESS';
export const PORTFOLIO_ERROR = 'PORTFOLIO_ERROR';
export const PORTFOLIO_UPDATE_CURRENCY = 'PORTFOLIO_UPDATE_CURRENCY';
export const PORTFOLIO_ADD_TRANSACTION = 'PORTFOLIO_ADD_TRANSACTION';
export const PORTFOLIO_ACTUALIZE_ITEM = 'PORTFOLIO_ACTUALIZE_ITEM';
export const PORTFOLIO_ACTUALIZE_NETCOSTS = 'PORTFOLIO_ACTUALIZE_NETCOSTS';
export const PORTFOLIO_UPDATE_ITEM_CURRENCY = 'PORTFOLIO_UPDATE_ITEM_CURRENCY';