export const MARKETDATA_USERCOINS_SUCCESS = 'MARKETDATA_USERCOINS_SUCCESS';
export const MARKETDATA_ALLCOINSLIST_SUCCESS = 'MARKETDATA_ALLCOINSLIST_SUCCESS';
export const MARKETDATA_ERROR = 'MARKETDATA_ERROR';
export const MARKETDATA_ADDCOIN_TO_USERCOINS = 'MARKETDATA_ADDCOIN_TO_USERCOINS';
export const MARKETDATA_GLOBAL_MARKET_DATA = 'MARKETDATA_GLOBAL_MARKET_DATA';