export const WATCHLIST_SUCCESS = 'WATCHLIST_SUCCESS';
export const WATCHLIST_ERROR = 'WATCHLIST_ERROR';
export const WATCHLIST_CHANGE_COIN_CURRENCY = 'WATCHLIST_CHANGE_COIN_CURRENCY';
export const WATCHLIST_ADD_NEW_COIN = 'WATCHLIST_ADD_NEW_COIN';
export const WATCHLIST_DELETE_COIN = 'WATCHLIST_DELETE_COIN';